---

- name: Ensure AWS directory
  file:
    path: "{{ aws_directory }}"
    state: directory
  when:
  - aws_creds_type == "file"

- name: Generate AWS cred files
  template:
    src: "aws_credentials.j2"
    dest: "{{ aws_directory }}"
  when:
  - aws_creds_type == "file"

- name: ECR Login script
  template:
    src: "docker-credential-ecr-login.{{ aws_creds_type }}.j2"
    dest: "{{ bin_path }}/docker-credential-ecr-login"
    mode: 0755

- name: Ensure Docker directory
  file:
    path: "{{ docker_directory }}"
    state: directory

- name: Docker config
  copy:
    src: config.json
    dest: "{{ docker_directory }}"
